---
title: "hw-01"
author: "Nanshuyuan Zhang (S2516281)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}    
knitr::opts_chunk$set(out.width = "100%")
```


------------------------------------------------------------------------------

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)
library(lubridate)
```

```{r load-data, message=FALSE}
edibnb <- read_csv("data/edibnb.csv")
council <- read_csv("data/council_assessments.csv")
```

------------------------------------------------------------------------------


## EXERCISE 1

```{r hw1-ex1}
na_columns <- colnames(edibnb)[colSums(is.na(edibnb)) > 0]
na_columns

edibnb %>% 
  filter(review_scores_rating == 100)%>%
  arrange(desc(number_of_reviews))

```


The variables with missing observations are showed.Finding columns with NA.
The table showes id which all has 100 review_scores_rating with highest number of reviews.

------------------------------------------------------------------------------

## EXERCISE 2

```{r hw1-ex2}
edibnb %>%
  filter(
    neighbourhood == "Old Town",
    price > 100
    )%>%
  count()

properties_four <- edibnb %>%
  filter(
    neighbourhood == "Southside",
    accommodates >= 4
  )
properties_four %>%
  summarise(
    mean_price = mean(price),
    minimum_price = min(price),
    maximum_price = max(price)
  )

```


There has 552 number of Airbnb properties located in Old Town having the one night stay price larger than 100 GBP.
For Airbnb properties in Southside for a single night stay for four people, the minimum price is 10, maximum price is 800, and average price is 153.1368. 



------------------------------------------------------------------------------

## EXERCISE 3

```{r hw1-ex3}
edibnb %>%
  filter(neighbourhood == "Newington")%>%
  count(bathrooms)

edibnb %>%
  mutate(new_bathrooms = ceiling(bathrooms))%>%
  filter(new_bathrooms > bedrooms, na.rm = TRUE)%>%
  summarise(count=n())


```


The number of properties that has bathroom more than bedrooms in Edinburgh is 703.


------------------------------------------------------------------------------

## EXERCISE 4

```{r hw1-ex4}
council %>%
  mutate(
    final_date = dmy(assessment_date)
    )%>%
  filter(month(final_date) == 05)%>%
  summarise(
    count = n()
  )

New_set = right_join(edibnb,council)
New_set %>%
  select(neighbourhood)%>%
  group_by(neighbourhood)%>%
  summarise(count = n())

```


The frequency table shows number of properties in different area. As the properties in Leith is too large, therefore the council is not targeting all neighborhoods equally.
Yes, there is.Compare the proportions.Count the number of properties in each neighborhood and sum the number of properties in each neighborhood, then calculate the proportion assessed.


------------------------------------------------------------------------------
